# Generated by Django 4.2.4 on 2023-08-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0002_healthservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='doctor.jpg', upload_to='doctor')),
                ('twitter', models.CharField(default='#', max_length=255)),
                ('facebook', models.CharField(default='#', max_length=255)),
                ('instagram', models.CharField(default='#', max_length=255)),
                ('linkdin', models.CharField(default='#', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='root.skills')),
            ],
        ),
    ]
